/*
*
*    Copyright (c) 1996-2002, Valve LLC. All rights reserved.
*
*    This product contains software technology licensed from Id
*    Software, Inc. ("Id Technology").  Id Technology (c) 1996 Id Software, Inc.
*    All Rights Reserved.
*
*    Use, distribution, and modification of this source code and/or resulting
*    object code is restricted to non-commercial enhancements to products from
*    Valve LLC.  All other use, distribution, or modification is prohibited
*    without written permission from Valve LLC.
*
*/

#pragma once

#if !defined(_HW)

// Macros for exported engine funcs, but nulls
#define RecEngSPR_Load(...)
#define RecEngSPR_Frames(...)
#define RecEngSPR_Height(...)
#define RecEngSPR_Width(...)
#define RecEngSPR_Set(...)
#define RecEngSPR_Draw(...)
#define RecEngSPR_DrawHoles(...)
#define RecEngSPR_DrawAdditive(...)
#define RecEngSPR_EnableScissor(...)
#define RecEngSPR_DisableScissor(...)
#define RecEngSPR_GetList(...)
#define RecEngDraw_FillRGBA(...)
#define RecEnghudGetScreenInfo(...)
#define RecEngSetCrosshair(...)
#define RecEnghudRegisterVariable(...)
#define RecEnghudGetCvarFloat(...)
#define RecEnghudGetCvarString(...)
#define RecEnghudAddCommand(...)
#define RecEnghudHookUserMsg(...)
#define RecEnghudServerCmd(...)
#define RecEnghudClientCmd(...)
#define RecEnghudFilteredClientCmd(...)
#define RecEngPrimeMusicStream(...)
#define RecEnghudGetPlayerInfo(...)
#define RecEnghudPlaySoundByName(...)
#define RecEnghudPlaySoundByNameAtPitch(...)
#define RecEnghudPlaySoundVoiceByName(...)
#define RecEnghudPlaySoundByIndex(...)
#define RecEngAngleVectors(...)
#define RecEngTextMessageGet(...)
#define RecEngTextMessageDrawCharacter(...)
#define RecEngDrawConsoleString(...)
#define RecEngDrawSetTextColor(...)
#define RecEnghudDrawConsoleStringLen(...)
#define RecEnghudConsolePrint(...)
#define RecEnghudCenterPrint(...)
#define RecEnghudCenterX(...)
#define RecEnghudCenterY(...)
#define RecEnghudGetViewAngles(...)
#define RecEnghudSetViewAngles(...)
#define RecEnghudGetMaxClients(...)
#define RecEngCvar_SetValue(...)
#define RecEngCmd_Argc(...)
#define RecEngCmd_Argv(...)
#define RecEngCon_Printf(...)
#define RecEngCon_DPrintf(...)
#define RecEngCon_NPrintf(...)
#define RecEngCon_NXPrintf(...)
#define RecEnghudPhysInfo_ValueForKey(...)
#define RecEnghudServerInfo_ValueForKey(...)
#define RecEnghudGetClientMaxspeed(...)
#define RecEnghudCheckParm(...)
#define RecEngKey_Event(...)
#define RecEnghudGetMousePosition(...)
#define RecEnghudIsNoClipping(...)
#define RecEnghudGetLocalPlayer(...)
#define RecEnghudGetViewModel(...)
#define RecEnghudGetEntityByIndex(...)
#define RecEnghudGetClientTime(...)
#define RecEngV_CalcShake(...)
#define RecEngV_ApplyShake(...)
#define RecEngPM_PointContents(...)
#define RecEngPM_WaterEntity(...)
#define RecEngPM_TraceLine(...)
#define RecEngCL_LoadModel(...)
#define RecEngCL_CreateVisibleEntity(...)
#define RecEnghudGetSpritePointer(...)
#define RecEnghudPlaySoundByNameAtLocation(...)
#define RecEnghudPrecacheEvent(...)
#define RecEnghudPlaybackEvent(...)
#define RecEnghudWeaponAnim(...)
#define RecEngRandomFloat(...)
#define RecEngRandomLong(...)
#define RecEngCL_HookEvent(...)
#define RecEngCon_IsVisible(...)
#define RecEnghudGetGameDir(...)
#define RecEngCvar_FindVar(...)
#define RecEngKey_NameForBinding(...)
#define RecEnghudGetLevelName(...)
#define RecEnghudGetScreenFade(...)
#define RecEnghudSetScreenFade(...)
#define RecEngVGuiWrap_GetPanel(...)
#define RecEngVGui_ViewportPaintBackground(...)
#define RecEngCOM_LoadFile(...)
#define RecEngCOM_ParseFile(...)
#define RecEngCOM_FreeFile(...)
#define RecEngCL_IsSpectateOnly(...)
#define RecEngR_LoadMapSprite(...)
#define RecEngCOM_AddAppDirectoryToSearchPath(...)
#define RecEngClientDLL_ExpandFileName(...)
#define RecEngPlayerInfo_ValueForKey(...)
#define RecEngPlayerInfo_SetValueForKey(...)
#define RecEngGetPlayerUniqueID(...)
#define RecEngGetTrackerIDForPlayer(...)
#define RecEngGetPlayerForTrackerID(...)
#define RecEnghudServerCmdUnreliable(...)
#define RecEngGetMousePos(...)
#define RecEngSetMousePos(...)
#define RecEngSetMouseEnable(...)
#define RecEngSetFilterMode(...)
#define RecEngSetFilterColor(...)
#define RecEngSetFilterBrightness(...)
#define RecEngSequenceGet(...)
#define RecEngSPR_DrawGeneric(...)
#define RecEngSequencePickSentence(...)
#define RecEngLocalPlayerInfo_ValueForKey(...)
#define RecEngProcessTutorMessageDecayBuffer(...)
#define RecEngConstructTutorMessageDecayBuffer(...)
#define RecEngResetTutorMessageDecayBuffer(...)
#define RecEngDraw_FillRGBABlend(...)

#endif // #if !defined(_HW)
